import Head from 'next/head'
import Image from 'next/image'
//import { Inter } from '@next/font/google'
import Inter from '@next/font/google'
import styles from '../styles/Home.module.css'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Site in development...
          </p>
        </div>

        <div className={styles.center}>
          Akihiko Shirai in Laval Virtual &nbsp;  
          <Image
            className={styles.logo}
            src="HakaseQR.png"
            alt="Next.js Logo"
            width={180}
            height={180}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="http://j.mp/ReVo18photo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.container}>
            ReVo18
            </h2>
            <p className={styles.container}>
              Find photo in Laval Virtual ReVolution 2018.
            </p>
          </a>

          <a
            href="https://github.com/kaitas/ReVolution"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.container}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={styles.container}>
              Discover past template in 2014.
            </p>
          </a>

        </div>
      </main>
    </>
  )
}
